spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: junwoo1027
    password: 1027
    url: jdbc:mysql://localhost:3306/testdb?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Seoul
    hikari:
      connection-test-query: SELECT 1
    hibernate.naming:
     physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
     implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy

  jpa:
    hibernate.ddl-auto: update
    hibernate.naming:
      physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#    show-sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace